# Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Aean's Post
tagline:          'A Jekyll theme'
description:      'I am a postgrad student at Institute of Computing Technology, Chinese Academy of Sciences.'
url:              http://aean.net

author:
  name:           'Aean'
  url:            mailto:v@aean.net

paginate:         5

# Custom vars
version:          2.0.0

github:           
  repo:           https://github.com/AeanSR/AeanSR.github.io/
